In [1]:
# installing required modules
! pip install pandas
! pip install nltk
! pip install scikit-learn
! pip install streamlit
! pip install joblib

Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: nltk in ./.venv/lib/python3.13/site-packages (3.9.4)
Requirement already satisfied: click in ./.venv/lib/python3.13/site-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in ./.venv/lib/python3.13/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in ./.venv/lib/python3.13/site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in ./.venv/lib/python3.13/site-packages (from nltk) (4.67.3)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.13/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in ./.venv/lib/python3.13/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in ./.venv/lib/python3.13/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in ./.venv/lib/python3.13/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./.venv/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: streamlit in ./.venv/lib/python3.13/site-packages (1.57.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (6.1.0)
Requirement already satisfied: blinker<2,>=1.5.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in ./.venv/lib/python3.13/site-packages (from streamlit) (7.1.1)
Requirement already satisfied: click<9,>=7.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (8.3.3)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in ./.venv/lib/python3.13/site-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in ./.venv/lib/python3.13/site-packages (from streamlit) (2.4.4)
Requirement already satisfied: packaging>=20 in ./.venv/lib/python3.13/site-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (3.0.2)
Requirement already satisfied: pillow<13,>=7.1.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (12.2.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in ./.venv/lib/python3.13/site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in ./.venv/lib/python3.13/site-packages (from streamlit) (7.34.1)
Requirement already satisfied: pyarrow>=7.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in ./.venv/lib/python3.13/site-packages (from streamlit) (2.33.1)
Requirement already satisfied: tenacity<10,>=8.1.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in ./.venv/lib/python3.13/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (1.0.0)
Requirement already satisfied: uvicorn>=0.30.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in ./.venv/lib/python3.13/site-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in ./.venv/lib/python3.13/site-packages (from streamlit) (0.0.27)
Requirement already satisfied: websockets>=12.0.0 in ./.venv/lib/python3.13/site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in ./.venv/lib/python3.13/site-packages (from streamlit) (2.2.0)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in ./.venv/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in ./.venv/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.21.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./.venv/lib/python3.13/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in ./.venv/lib/python3.13/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2026.4.22)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.13/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in ./.venv/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.venv/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in ./.venv/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in ./.venv/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: h11>=0.8 in ./.venv/lib/python3.13/site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: joblib in ./.venv/lib/python3.13/site-packages (1.5.3)

In [2]:
### import commands
import pandas as pd
import re
import joblib 
import pickle
import nltk

from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/genaienggkomalgore/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/genaienggkomalgore/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/genaienggkomalgore/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [5]:
stopword_list = stopwords.words('english')
print(stopword_list)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

===================================================================
## Assignment 20: Building & Deploying a Recommendation System
===================================================================

------------------------------------------
# PART 1 — Data Preprocessing
------------------------------------------

## Task 1: Load & Understand Dataset
1. Load the dataset using Pandas.
2. Print:
    - Dataset shape
    - Column names 
    - First 5 rows
    - Other essential Details
3. Identify text column(s) used for recommendations.

Download [dataset](https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata) from here.

In [6]:
# ## Task 1: Load & Understand Dataset

path_credits = "Dataset/tmdb_5000_credits.csv"
path_movies = "Dataset/tmdb_5000_movies.csv"


# 1. Load the dataset using Pandas.

credits = pd.read_csv(path_credits)
movies = pd.read_csv(path_movies)

# 2. Print:
#     - Dataset shape
print("*"*100)
print(f"Dataset Shape : \nMovie : {movies.shape} \nCredits : {credits.shape}")
print("*"*100)

#     - Column names 

print(f"Column names : \nMovie : {movies.columns} \nCredits : {credits.columns}")
print("*"*100)
#     - First 5 rows
print(f"First 5 rows : \nMovie : {movies.head()} {"#"*100}\n\nCredits : {credits.head()}")
print("*"*100)
#     - Other essential Details

print(f"Describe : \nMovie : {movies.describe()} {"#"*100}\n\nCredits : {credits.describe()}")
print("*"*100)

print(f"IsNULL : \nMovie : {movies.isnull().sum()} {"#"*100}\n\nCredits : {credits.isnull().sum()}")
print("*"*100)

print(f"Duplicated Values : \nMovie : {movies.duplicated().sum()} {"#"*100}\n\nCredits : {credits.duplicated().sum()}")
print("*"*100)


# 3. Identify text column(s) used for recommendations.

****************************************************************************************************
Dataset Shape :
Movie : (4803, 20)
Credits : (4803, 4)
****************************************************************************************************
Column names :
Movie : Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')
Credits : Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')
****************************************************************************************************
First 5 rows :
Movie :       budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4  [{"id": 818, "name": "based on novel"}, {"id":...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bond’s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...
3  [{"name": "Legendary Pictures", "id": 923}, {"...
4        [{"name": "Walt Disney Pictures", "id": 2}]

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                      title  vote_average  vote_count
0                                    Avatar           7.2       11800
1  Pirates of the Caribbean: At World's End           6.9        4500
2                                   Spectre           6.3        4466
3                     The Dark Knight Rises           7.6        9106
4                               John Carter           6.1        2124   ####################################################################################################

Credits :    movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...
1  [{"cast_id": 4, "character": "Captain Jack Spa...
2  [{"cast_id": 1, "character": "James Bond", "cr...
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4  [{"cast_id": 5, "character": "John Carter", "c...

                                                crew
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
****************************************************************************************************
Describe :
Movie :              budget             id   popularity       revenue      runtime  \
count  4.803000e+03    4803.000000  4803.000000  4.803000e+03  4801.000000
mean   2.904504e+07   57165.484281    21.492301  8.226064e+07   106.875859
std    4.072239e+07   88694.614033    31.816650  1.628571e+08    22.611935
min    0.000000e+00       5.000000     0.000000  0.000000e+00     0.000000
25%    7.900000e+05    9014.500000     4.668070  0.000000e+00    94.000000
50%    1.500000e+07   14629.000000    12.921594  1.917000e+07   103.000000
75%    4.000000e+07   58610.500000    28.313505  9.291719e+07   118.000000
max    3.800000e+08  459488.000000   875.581305  2.787965e+09   338.000000

       vote_average    vote_count
count   4803.000000   4803.000000
mean       6.092172    690.217989
std        1.194612   1234.585891
min        0.000000      0.000000
25%        5.600000     54.000000
50%        6.200000    235.000000
75%        6.800000    737.000000
max       10.000000  13752.000000   ####################################################################################################

Credits :             movie_id
count    4803.000000
mean    57165.484281
std     88694.614033
min         5.000000
25%      9014.500000
50%     14629.000000
75%     58610.500000
max    459488.000000
****************************************************************************************************
IsNULL :
Movie : budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64 ####################################################################################################

Credits : movie_id    0
title       0
cast        0
crew        0
dtype: int64
****************************************************************************************************
Duplicated Values :
Movie : 0 ####################################################################################################

Credits : 0
****************************************************************************************************

In [7]:
movies.rename(columns= {'id':'movie_id'},inplace= True)

In [8]:
df = pd.merge(movies , credits , on = 'movie_id')
df.columns

# colunmns we don't  need : 
col_names = ['budget', 'homepage','original_title', 'movie_id', 'keywords','original_language', 'production_companies', 'production_countries', 'release_date','revenue', 'runtime', 'spoken_languages', 'status','title_x', 'vote_average', 'vote_count','popularity'] 
df.drop(columns= col_names , inplace=True)
df = df.dropna()
df.rename(columns= {"title_y":"title"},inplace= True)
# df.info()

In [9]:
df['tagline'].isna().sum()

np.int64(0)

## Task 2: Text Preprocessing for Recommendation
Apply the following steps on the text column:
1. Convert text to lowercase
2. Remove punctuation and special characters
3. Remove stopwords
4. Handle missing values (replace with empty string)
Store cleaned text in a new column: clean_text.

In [10]:
df['tagline'] = df['tagline'].fillna('',inplace=True)

/var/folders/n_/7z9tgm7508z7_wn1z6d0p3fw0000gn/T/ipykernel_40711/1874935130.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['tagline'] = df['tagline'].fillna('',inplace=True)

In [11]:
df['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [12]:
import json

In [13]:
def top_5_cast(data):
    result = []
    json_data = json.loads(data)
    for i in range(0,5):
        try:
            result.append(json_data[i]['name'])
        except IndexError:
            break
        

    return " ".join(result)

df['cast'] = df['cast'].apply(lambda data : top_5_cast(data))

In [14]:
# crew
def get_director(data):
    json_data = json.loads(data)
    result = []
    for i in json_data:
        if i['job']== "Director":
            result.append(i['name'])
    return " ".join(result)

df['crew'] = df['crew'].apply(lambda data : get_director(data))

In [15]:
# genres

def get_genres(data):
    json_data = json.loads(data)
    result = []
    for i in json_data:
        result.append(i['name'])
    return " ".join(result)

#get_genres(df['genres'][0])
df['genres'] = df['genres'].apply(lambda data : get_genres(data))

In [16]:
df.head()

,genres,overview,tagline,title,cast,crew
0,Action Adventure Fantasy Science Fiction,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,Avatar,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron
1,Adventure Fantasy Action,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski
2,Action Adventure Crime,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,Spectre,Daniel Craig Christoph Waltz Léa Seydoux Ralph...,Sam Mendes
3,Action Crime Drama Thriller,Following the death of District Attorney Harve...,The Legend Ends,The Dark Knight Rises,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan
4,Action Adventure Science Fiction,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",John Carter,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton

In [17]:
def stop_word_removal(data):
    result = []
    for i in data.split():
        if i not in stopword_list:
            result.append(i)
    return " ".join(result)

In [18]:
col_names = list(df.columns)

col_names.remove("title")

In [19]:
# Apply the following steps on the text column:



# 1. Convert text to lowercase

df['tagline'] = df['tagline'].apply(lambda data : str(data))

for i in col_names:
    df[i] = df[i].apply(lambda data : data.lower())
    
# 2. Remove punctuation and special characters

for i in col_names:
    df[i] = df[i].apply(lambda data : re.sub(r"[^\w ^\d]"," ",data))
   

# 3. Remove stopwords

for i in col_names:
    df[i] = df[i].apply(lambda data : stop_word_removal(data))
   

# 4. Handle missing values (replace with empty string)

# already done
   
# remove digit

for i in col_names:
    df[i] = df[i].apply(lambda data : re.sub(r'[1234567890]','',data))


# Store cleaned text in a new column: clean_text.
df['clean_text'] = df['crew'] + " " +df['genres'] + " " + df['overview']+ " " +df['tagline'] + " " +df['cast']

In [20]:
df.head()

,genres,overview,tagline,title,cast,crew,clean_text
0,action adventure fantasy science fiction,nd century paraplegic marine dispatched moon p...,enter world pandora,Avatar,sam worthington zoe saldana sigourney weaver s...,james cameron,james cameron action adventure fantasy science...
1,adventure fantasy action,captain barbossa long believed dead come back ...,end world adventure begins,Pirates of the Caribbean: At World's End,johnny depp orlando bloom keira knightley stel...,gore verbinski,gore verbinski adventure fantasy action captai...
2,action adventure crime,cryptic message bond past sends trail uncover ...,plan one escapes,Spectre,daniel craig christoph waltz léa seydoux ralph...,sam mendes,sam mendes action adventure crime cryptic mess...
3,action crime drama thriller,following death district attorney harvey dent ...,legend ends,The Dark Knight Rises,christian bale michael caine gary oldman anne ...,christopher nolan,christopher nolan action crime drama thriller ...
4,action adventure science fiction,john carter war weary former military captain ...,lost world found another,John Carter,taylor kitsch lynn collins samantha morton wil...,andrew stanton,andrew stanton action adventure science fictio...

In [21]:
# drop other collunms

df.drop(columns= col_names , inplace = True)

In [22]:
df.reset_index(inplace=True)

In [23]:
df.head()

,index,title,clean_text
0,0,Avatar,james cameron action adventure fantasy science...
1,1,Pirates of the Caribbean: At World's End,gore verbinski adventure fantasy action captai...
2,2,Spectre,sam mendes action adventure crime cryptic mess...
3,3,The Dark Knight Rises,christopher nolan action crime drama thriller ...
4,4,John Carter,andrew stanton action adventure science fictio...

------------------------------------------
# PART 2 — Text Vectorization
------------------------------------------

## Task 3: Vectorization using TF-IDF
1. Use TfidfVectorizer) to convert text into vectors.
2. Set reasonable parameters:
    - max_features
    - ngram_range
3. Display:
    - Shape of TF-IDF matrix

In [ ]:
# ## Task 3: Vectorization using TF-IDF
# 1. Use TfidfVectorizer) to convert text into vectors.

tidf = TfidfVectorizer( max_features= 3500 , ngram_range=(1,1))

Y = df['title']

X = tidf.fit_transform(df['clean_text'])
result = X.toarray()
# 2. Set reasonable parameters:
#     - max_features
#     - ngram_range
# 3. Display:
#     - Shape of TF-IDF matrix

print(f"Shape of TF-IDF matrix : {result.shape}")

Shape of TF-IDF matrix : (3959, 3500)

KeyboardInterrupt:

## Task 4: Similarity Computation
1. Compute cosine similarity between all items.
2. Store similarity matrix.
3. Explain briefly why cosine similarity is used.

In [ ]:
# ## Task 4: Similarity Computation
# 1. Compute cosine similarity between all items.

similarity = cosine_similarity(result)

# 2. Store similarity matrix.

print(similarity)

# 3. Explain briefly why cosine similarity is used.

# TO DO

[[1.         0.04584518 0.03527537 ... 0.04087836 0.         0.03716042]
 [0.04584518 1.         0.03502503 ... 0.02244027 0.         0.01869092]
 [0.03527537 0.03502503 1.         ... 0.0125013  0.         0.07713974]
 ...
 [0.04087836 0.02244027 0.0125013  ... 1.         0.         0.00888758]
 [0.         0.         0.         ... 0.         1.         0.00757474]
 [0.03716042 0.01869092 0.07713974 ... 0.00888758 0.00757474 1.        ]]

In [ ]:
tidf.idf_

array([5.18965474, 5.91670347, 6.79909265, ..., 6.71904995, 6.33956033,
       6.98141421], shape=(3500,))

In [ ]:
tidf.get_feature_names_out()

array(['aaron', 'abandoned', 'abducted', ..., 'zone', 'zooey', 'zucker'],
      shape=(3500,), dtype=object)

------------------------------------------

# PART 3 — Recommendation Logic

------------------------------------------

## Task 5: Build Recommendation Function
Create a function:

```def recommend(item_name, top_n=5):```

```returns top N similar items```

Function should:
1. Find index of the selected item
2. Compute similarity scores
3. Sort and return top recommendations
Test with at least 3 different items.
+

In [ ]:
# ## Task 5: Build Recommendation Function
# Create a function:

# ```def recommend(item_name, top_n=5):```

def recommend(item_name, top_n =5):
    result = []
    index = df[df['title']==item_name].index[0]
    responce = similarity[index]
    value = sorted(enumerate(responce), key= lambda x : x[1], reverse= True)[1:top_n+1]
    for i in value:
        result.append(df['title'][i[0]])
        
    


    return result
# ```returns top N similar items```



# Function should:
# 1. Find index of the selected item2. Compute similarity scores
# 3. Sort and return top recommendations
# Test with at least 3 different items.
print(recommend(df['title'][5]))
print(recommend(df['title'][5],1))
print(recommend(df['title'][5],3))

['Spider-Man 2', 'Spider-Man', 'Arachnophobia', 'The Amazing Spider-Man', 'The Amazing Spider-Man 2']
['Spider-Man 2']
['Spider-Man 2', 'Spider-Man', 'Arachnophobia']

In [ ]:
# Creating file

joblib.dump(similarity,'similarities.joblib',compress=3)

# Save data to a binary file
with open("dataset.dat", "wb") as f:
    pickle.dump(df, f)

#

------------------------------------------
# PART 4 — Simple App Interface
------------------------------------------

## Task 6: Build Ul using Streamlit
1. Create a simple interface:
• Dropdown to select item
• Button to generate recommendations
2. Display recommended items clearly.
You may use:
Streamlit (preferred)

In [ ]:
# All code is in main.py file

import os
path = os.getcwd()+"/app.py"

os.system(f"streamlit run {path}")

2026-05-08 18:54:55.621 Uvicorn server started on 0.0.0.0:8502

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://192.168.29.87:8502

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog

Aliens
Apollo 18
Colombiana
Aliens vs Predator: Requiem
Guardians of the Galaxy
Aliens
Apollo 18
Colombiana
Aliens vs Predator: Requiem
Guardians of the Galaxy
Aliens
Apollo 18
Colombiana
Aliens vs Predator: Requiem
Guardians of the Galaxy
Aliens
Apollo 18
Colombiana
Aliens vs Predator: Requiem
Guardians of the Galaxy
Aliens
Apollo 18
Colombiana
Aliens vs Predator: Requiem
Guardians of the Galaxy
Aliens<br>Apollo 18<br>Colombiana<br>Aliens vs Predator: Requiem<br>Guardians of the Galaxy
Aliens<br>Apollo 18<br>Colombiana<br>Aliens vs Predator: Requiem<br>Guardians of the Galaxy
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']

2026-05-08 18:56:50.120 Script compilation error
Traceback (most recent call last):
  File "/Users/genaienggkomalgore/Documents/Assignment/Assignment20/.venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in _run_script
    code = self._script_cache.get_bytecode(script_path)
  File "/Users/genaienggkomalgore/Documents/Assignment/Assignment20/.venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_cache.py", line 72, in get_bytecode
    filebody = magic.add_magic(filebody, script_path)
  File "/Users/genaienggkomalgore/Documents/Assignment/Assignment20/.venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/magic.py", line 45, in add_magic
    tree = ast.parse(code, script_path, "exec")
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
                   _feature_version=feature_version, optimize=optimize)
  File "/Users/genaienggkomalgore/Documents/Assignment/Assignment20/main.py", line 15
    st.write(i.,result[i])
               ^
SyntaxError: invalid syntax
2026-05-08 18:56:50.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
['Aliens', 'Apollo 18', 'Colombiana', 'Aliens vs Predator: Requiem', 'Guardians of the Galaxy']
  Stopping...

0

## PART 5 — Version Control with Git & GitHub

Task 7: Git & GitHub Setup
1. Initialize a Git repository.
2. Create a GitHub repository.
3. Push your project code to GitHub.
Repository must include:
app.py
requirements.txt
README.md

# DONE


------------------------------------------
# PART 6 - Deployment on Render
------------------------------------------

## Task 8: Deploy Application on Render
1. Create a Render account.
2. Connect Render with GitHub.
3. Select your repository.
4. Configure:
    - Build command
    - Start command

# 5. Deploy the application.
Task 9: Final Validation
1. Test deployed app link.
2. Ensure recommendations work correctly.
3. Include deployed URL in submission.